### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by Jeong29Hyeon** [Jeong29Hyeon/jpa-springboot#1]
### html 서버 재시작 없이 빌드하는법
**build.gradle에 추가후 html파일에서 ctrl + shift + f9**
`implementation 'org.springframework.boot:spring-boot-devtools'` 
***
### 쿼리 파라미터를 보기위한 2가지 방법
- 1. build.gradle 에 추가
  - `implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.5.6'` 
    - 참고: 쿼리 파라미터를 로그로 남기는 외부 라이브러리는 시스템 자원을 사용하므로,
개발 단계에서는 편하게 사용해도 된다. 하지만 운영시스템에 적용하려면 
꼭 성능테스트를 하고 사용하는 것이 좋다.
- 2. application.yml 에 추가
```
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace // SQL 쿼리 파라미터 보기
```
